spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

database:
  primary:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/primay?useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: ''
      driverClassName: com.mysql.jdbc.Driver

  secondary:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/secondary?useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: ''
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 8080
  servlet:
    path: /nitheesh/